---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Install Apache.
      yum: name={{ item }} state=latest
      with_items:
        - httpd
        - php
        - php-mysql
    - name: Download Wordpress
      get_url: url=http://wordpress.org/wordpress-5.1.3.tar.gz dest=/var/www/html/wordpress.tar.gz force=yes
    - name: Extract Wordpress
      command: "tar xzf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"
    - name: Make my dir readable
      file:
        path: /var/www/html
        mode: u=rwX,g=rX,o=rX
        recurse: yes
        owner: apache
        group: apache
    - name: Make  sure Apache is started now and at boot.
      service: name=httpd state=started enabled=yes
